import json
import random
import logging
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import (
    Application, CommandHandler, CallbackQueryHandler,
    ContextTypes
)

# ===================== SOZLAMALAR =====================
TOKEN = "8646811100:AAG9X338taNcl4v_ycj5MgybeZL8I8GpNBE"
QUESTIONS_PER_TEST = 20   # Har testda nechta savol
# ======================================================

logging.basicConfig(level=logging.INFO)

# =============== SAVOLLAR MA'LUMOTI ===================
QUESTIONS = [
  {"question": "\u201cTashkiliy xulq\u201d fanini o\u2019rganishdan asosiy maqsad \u2013", "answers": ["tashkilotda shaxs va  guruhning xulqini boshqarish usullarini egallashdan iborat", "tashkilotda guruhning xulqini boshqarish usullarini egallashdan iborat", "tashkilotda shaxs va  guruhning xulqini birgalikdagi  qo\u2019shib boshqarish usullarini egallashdan iborat", "tashkilotda shaxsning xulqini boshqarish usullarini egallashdan iborat"], "correct": 0},
  {"question": "Javoblarning qaysi birida  \u201cTashkiliy xulq\u201d fanining o\u2019rganish vazifalaridan biri to\u2019g\u2019ri ifoda etilgan?", "answers": ["bo\u2019lajak bakalavrlarda tashkiliy xulqning hozirgi holati va uning rivojlanish tendensiyalari haqida tasavvur hosil qilish", "markazida inson va tashkilot uning ehtiyojlari turadigan tashkiliy tizimlarni yaratish usullarini o\u2019rganish", "xodimlar va guruhning alohida, bir-biridan ajratilgan holda  tashkilotdagi xulqini ta\u2019riflash usullarini o\u2019rganish", "tashkilot faoliyatining samaradorligini oshirish maqsadida shaxsning indiviual  xulqini boshqarish ko\u2019nikmalarini berish"], "correct": 0},
  {"question": "Javoblarning qaysi birida  \u201cTashkiliy xulq\u201d fanining o\u2019rganish vazifalaridan biri to\u2019g\u2019ri ifoda etilagan?", "answers": ["markazida inson biologik ehtiyojlari turadigan tashkiliy tizimlarni yaratish usullarini o\u2019rganish", "markazida inson va uning ehtiyojlari turadigan tashkiliy tizimlarni yaratish usullarini o\u2019rganish", "markazida inson va uning olia a\u2019zolarning ehtiyojlari turadigan tashkiliy tizimlarni yaratish usullarini o\u2019rganish", "markazida inson va uning ijtiomiy-ruxiy ehtiyojlari turadigan tashkiliy tizimlarni yaratish usullarini o\u2019rganish"], "correct": 1},
  {"question": "Javoblarning qaysi birida  \u201cTashkiliy xulq\u201d fanining o\u2019rganish vazifalaridan biri to\u2019g\u2019ri ifoda etilagan?", "answers": ["xodimlar va guruhning tashkilotdagi alohida -alohida olingan  xulqini ta\u2019riflash usullarini o\u2019rganish", "xodimlar va guruhning tashkilotdagi xulqini o\u2019zaro ta\u2019sirini ta\u2019riflash usullarini o\u2019rganish", "xodimlar va guruhning tashkilotdagi xulqini ta\u2019riflash usullarini o\u2019rganish", "xodimlar va guruhning tashkilotdagi xulqlarini tashkilot manfaatlari nuqtai-nazardan ta\u2019riflash usullarini o\u2019rganish"], "correct": 3},
  {"question": "Javoblarning qaysi birida  \u201cTashkiliy xulq\u201d fanining o\u2019rganish vazifalaridan biri to\u2019g\u2019ri ifoda etilgan?", "answers": ["tashkilot faoliyatining samaradorligini oshirish maqsadida individ va guruhning xulqini tashkilot manfaatlari nuqtai-nazardan boshqarish ko\u2019nikmalarini berish", "tashkilot faoliyatining samaradorligini oshirish maqsadida guruhning xulqini boshqarish ko\u2019nikmalarini berish", "tashkilot faoliyatining samaradorligini oshirish maqsadida individ va guruhning xulqini boshqarish ko\u2019nikmalarini berish", "tashkilot faoliyatining samaradorligini oshirish maqsadida individ va guruhning alohida -alohida xulqlarini boshqarish ko\u2019nikmalarini berish"], "correct": 1},
  {"question": "\u00abTashkiliy xulq\u00bb fani nimani  o\u2019rganish uchun asos hisoblanadi?", "answers": ["individ va shaxs, tashkilot kabi asosiy komponentlarga tayangan holda boshqaruv fanlarining butun bir majmuini o\u2019rganish uchun asos hisoblanadi", "\u00abguruh va tashkilot kabi asosiy komponentlarga tayangan holda boshqaruv fanlarining butun bir majmuini o\u2019rganish uchun asos hisoblanadi", "individ va tashkilot kabi asosiy komponentlarga tayangan holda boshqaruv fanlarining butun bir majmuini o\u2019rganish uchun asos hisoblanadi", "individ, guruh va tashkilot kabi asosiy komponentlarga tayangan holda boshqaruv fanlarining butun bir majmuini o\u2019rganish uchun asos hisoblanadi"], "correct": 3},
  {"question": "Tashkiliy xulqni bilish menejerga: ", "answers": ["tashkilot xodimining saolohiyatini to\u2019liq ochib berish va uning faoliyatini qisman takomillashtirish yo\u2019nalishlarini tanlash;  markazida inson turadigan tashkiliy tuzilmalar loyihalari bo\u2019yicha takliflar ishlab chiqish; xodim mehnatini tashkil etishda konservatizmni istisno qilmaslik imkonini beruvchi kasbiy aralashuv strategiyasini belgilash imkonini beradi", "tashkilot xodimining saolohiyatini to\u2019liq ochib berish va uning faoliyatini takomillashtirish yo\u2019nalishlarini tanlash; markazida inson turadigan tashkiliy tuzilmalar loyihalarini ishlab chiqish; xodim mehnatini tashkil etishda konservatizmni istisno qilish imkonini beruvchi kasbiy aralashuv strategiyasini belgilash imkonini beradi", "tashkilot xodimining saolohiyatini to\u2019liq oshkor etmasdan va uning faoliyatini takomillashtirish yo\u2019nalishlarini tanlash; markazida inson turadigan tashkiliy tuzilmalar loyihalariga shartnomalar  ishlab chiqish; xodim mehnatini tashkil etishda konservatizmni istisno qilish imkonini beruvchi kasbiy aralashmaslik  strategiyasini belgilash imkonini beradi", "tashkilot xodimining saolohiyatini to\u2019liq ochib berish va uning faoliyatini tijorat yo\u2019nalishlarini tanlash; markazida inson turadigan tashkiliy tuzilmalar loyihachilari bilan shartnomalar imzolash; xodim mehnatini tashkil etishda konservatizmni istisno qilish imkonini beruvchi kasbiy aralashuv uchun  imkoniyat yaratish"], "correct": 1},
  {"question": "Tashkiliy xulq alohida ilmiy yo\u2019nalish sifatida qachon va qanday  paydo bo\u2019ldi?", "answers": ["tashkiliy xulq alohida ilmiy yo\u2019nalish sifatida 1960-yillarda menejmentda  yuz berayotgan jarayonlarni izohlash bilan shug\u2019ulanuvchi bir necha ilmiy xodimlarning  integratsiyalashuvi natijasida paydo bo\u2019ldi", "tashkiliy xulq alohida ilmiy yo\u2019nalish sifatida 1940-yillarda menejmentda har bir ish o\u2019rni darajasida va umuman tashkilotda yuz berayotgan jarayonlarni izohlash bilan shug\u2019ulanuvchi bir necha ilmiy xodimlar faoliyatini integratsiyalashuvi natijasida paydo bo\u2019ldi", "tashkiliy xulq alohida ilmiy yo\u2019nalish sifatida 1920-yillarda menejmentda  va umuman tashkilotda yuz berayotgan jarayonlarni izohlash bilan shug\u2019ulanuvchi bir necha ilmiy tadqiqot institutlar faoliyatlarning  integratsiyalashuvi natijasida paydo bo\u2019ldi", "tashkiliy xulq alohida ilmiy yo\u2019nalish sifatida 1960-yillarda menejmentda har bir ish o\u2019rni darajasida va umuman tashkilotda yuz berayotgan jarayonlarni izohlash bilan shug\u2019ulanuvchi bir necha ilmiy maktablarning integratsiyalashuvi natijasida paydo bo\u2019ldi"], "correct": 3},
  {"question": "Kimlar,  qaysi asar mualliflari  \"Tashkiliy xulq\" ilmiy yo\u2019nalishining asoschilari hisoblanadilar?", "answers": ["\u00abTrud i motivatsiya\u00bb (1954), deb nomlanuvchi mashhur ishi bir qator tarqoq ilmiy ishlarning yaxlit majmuaga integratsiyalauvini boshlab bergan V.Vrum, \u00abUpravlencheskie ustanovki i ix vypolnenie\u00bb (1968) asarining mualliflari L.Porter va E.Louler ushbu yo\u2019nalishning asoschilari hisoblanishadi", "\u00abUpravlencheskie ustanovki i ix vypolnenie\u00bb (1968) asarining mualliflari L.Porter va E.Louler ushbu yo\u2019nalishning asoschilari hisoblanishadi", "\u00abTrud i motivatsiya\u00bb (1954), deb nomlanuvchi mashhur ishi bir qator tarqoq ilmiy ishlarning yaxlit majmuaga integratsiyalauvini boshlab bergan V.Vrum, \u00abUpravlencheskie ustanovki i ix vypolnenie\u00bb (1968) asarining mualliflari L.Porter  ushbu yo\u2019nalishning asoschilari hisoblanishadi", "\u00abMotivatsiya va trud\u00bb (1956), deb nomlanuvchi mashhur ishi bir qator tarqoq ilmiy ishlarning yaxlit majmuaga integratsiyalauvini boshlab bergan V.Vrum va A.Maslou, \u00abUpravlencheskie ustanovki i ix vypolnenie\u00bb (1968) asarining mualliflari D. Makgregor,L.Porter va E.Louler ushbu yo\u2019nalishning asoschilari hisoblanishadi"], "correct": 0},
  {"question": "\u00abTashkiliy xulq\u00bb atamasini birinchi bo\u2019lib kim, qachon qo\u2019lladi va unda qanaqa mavzularni belgilab berdi?", "answers": ["\u00abtashkiliy xulq\u00bb atamasini birinchi bo\u2019lib V.I. Nabokov o\u2019zining shu nomli kitobida (1973) qo\u2019lladi. Unda olim bilimlarning mazkur sohasidagi ilmiy tadqiqotlarning asosiy mavzularini belgilab berdi: tushunish, ko\u2019rish va tashkilotlar doirasida inson xulqini boshqarish", "\u00abtashkiliy xulq\u00bb atamasini birinchi bo\u2019lib F.Lyutens o\u2019zining shu nomli kitobida (1973) qo\u2019lladi. Unda olim bilimlarning mazkur sohasidagi ilmiy tadqiqotlarning asosiy mavzularini belgilab berdi: tushunish, oldindan ko\u2019rish va tashkilotlar doirasida inson xulqini boshqarish", "\u00abtashkiliy xulq\u00bb atamasini birinchi bo\u2019lib F.Engels o\u2019zining shu nomli kitobida (1973) qo\u2019lladi. Unda olim bilimlarning mazkur sohasidagi ilmiy tadqiqotlarning asosiy mavzularini belgilab berdi: tushunish, oldindan ko\u2019rish va tashkilotlar doirasida inson xulqini boshqarish", "\u00abtashkiliy xulq\u00bb atamasini birinchi bo\u2019lib K.Mark va F.Engelslar Lyutens bilan hamkorlikda yozilgan  \"Kapital\"  nomli kitobida (1973) qo\u2019lladi. Unda olim bilimlarning mazkur sohasidagi ilmiy tadqiqotlarning asosiy mavzularini belgilab berdi: tushunish, oldindan ko\u2019rish va tashkilotlar doirasida inson xulqini boshqarish"], "correct": 1},
  {"question": "Tashkiliy xulq fan sifatida menejmentning o\u2019rnini egallaydimi va u menejmentning qaysi  jihatini o\u2019rganadi?", "answers": ["tashkiliy xulq fan sifatida menejmentning o\u2019rnini qisman egallaydi. U menejmentning xulqiy jihatini o\u2019rganadi", "tashkiliy xulq fan sifatida menejmentning qisman o\u2019rnini egallamaydi. U menejmentning faqat huquqiy jihatini o\u2019rganadi", "tashkiliy xulq fan sifatida menejmentning o\u2019rnini egallamaydi. U menejmentning xulqiy jihatini o\u2019rganadi", "tashkiliy xulq fan sifatida menejmentning qisman o\u2019rnini egallaydi. U menejmentning xulqiy jihatini o\u2019rganmaydi"], "correct": 2},
  {"question": "Zamonaviy menejer insonlarning mehnat xulqi haqida nimalarni bilishi kerak, uning bilimlari nimani oshishiga yordam beradi?", "answers": ["aynan ushbu sohalarda tashkiliy xulq qonuniyatlarini bilish tashkilot samaradorligining sezilarli darajada oshirishga yordam beradi", "tashkiliy xulq qonuniyatlarini bilish tashkilot raqobatbardoshligi darajasini  sezilarli darajada oshirishga yordam beradi", "zamonaviy menejer insonlarning mehnat xulqi haqida juda ko\u2019p narsa bilishi, shaxslararo kommunikatsiya tizimini  yaxshilash imkoniyatini tadqiq eta olishi va insonlarni  AKT yordamida boshqarishni bilishi zarur; tashkiliy xulq qonuniyatlarini bilish tashkilot raqobatbardoshligi darajasini  sezilarli darajada pasayishiga  yordam beradi", "zamonaviy menejer insonlarning mehnat xulqi haqida juda ko\u2019p narsa bilishi, shaxslararo munosabatlarni yaxshilash imkoniyatini tadqiq eta olishi va insonlar bilan o\u2019zaro munosabatlarni boshqarishni bilishi zarur; aynan ushbu sohalarda tashkiliy xulq qonuniyatlarini bilish tashkilot faoliyat ko\u2019rsatishining samaradorligini sezilarli darajada oshirishga yordam beradi"], "correct": 3},
  {"question": "Insonning tashkilotdagi xulqi qanaqa tarkibiy qismlar ta\u2019siridan shakllanadi?", "answers": ["insonning tashkilotdagi xulqi bir-biri bilan uzviy bog\u2019langan ikkita tarkibiy qism: shaxsiy xususiyatlar (tug\u2019ma xususiyatlar va ular asosida ortirilgan xususiyatlar) va insonning atrofidagi muhitning ta\u2019siridan shakllanadi", "insonning tashkilotdagi xulqi bir-biri bilan uzviy bog\u2019lanmagan uchta ikkita tarkibiy qism: shaxsiy xususiyatlar (tug\u2019ma xususiyatlar va ular asosida ortirilgan xususiyatlar) va insonning atrofidagi muhitning ta\u2019siridan shakllanadi", "insonning tashkilotdagi xulqi bir-biri bilan uzviy bog\u2019langan uchta tarkibiy qism: shaxsiy xususiyatlar (tug\u2019ma xususiyatlar, ular asosida ortirilgan xususiyatlar) va insonning atrofidagilar ta\u2019sirida vujudga kelagan muhitda  shakllanadi", "insonning tashkilotdagi xulqi bir-biri bilan uzviy bog\u2019lanmagan uchta ikkita tarkibiy qism: shaxsiy xususiyatlar (tug\u2019ma xususiyatlar va ular asosida ortirilgan xususiyatlar) va alohida insonning atrofidagi muhitning ta\u2019siridan shakllanadi"], "correct": 0},
  {"question": "Ilmiy menejment konsepsiyasining asoschisi F.Teylor, xodimlar va menejerlarga qanday toifa sifatida tan bergan edi?", "answers": ["ilmiy menejment konsepsiyasining asoschisi  F.Teylor, xodimlarni ishlab chiqarish omillaridan biri sifatida, menejerlarni esa boshqarish funksiyalarini bajarish uchun xodimlarning alohida toifasi sifatida tan olgandi.", "ilmiy menejment konsepsiyasining asoschisi  F.Teylor, xodimlarni ishlab chiqarish omillarinigg asosiysi sifatida, menejerlarni esa boshqarish funksiyalarini bajarish uchun xodimlarga rdamchi toifasi sifatida tan olgandi.", "ilmiy menejment konsepsiyasining asoschisi  F.Teylor, xodimlarni ishlab chiqarish omillaridanyordamchisi sifatida, menejerlarni esa boshqarish funksiyalarini bajarish uchun xodimlar bilan birgalikdagi  toifasi sifatida tan olgandi.", "ilmiy menejment konsepsiyasining asoschisi, F.Teylor, xodimlarni ishlab chiqarishning asosiy omili  sifatida, menejerlarni boshqarish  funksiyalarini bajarishda xodimlarning kompaleks toifasi sifatida tan olgandi."], "correct": 0},
  {"question": "Eng yuqori mehnat unumdorligiga erishishni qanday oqilona rejim ta\u2019minlashi kerak?", "answers": ["eng yuqori mehnat unumdorligiga erishish mehnatni ilmiy jihatdan tashkil etish va me\u2019yorlash, inson faoliyatidagi sun\u2019iy cheklovlarni hisobga oluvchi mehnat qilishning oqilona rejimi hisobidan ta\u2019minlanishi kerak", "eng yuqori mehnat unumdorligiga erishish mehnatni ilmiy jihatdan tashkil etish va me\u2019yorlash, inson faoliyatidagi tabiiy cheklovlarni hisobga oluvchi mehnat qilish va dam olishning oqilona rejimi hisobidan ta\u2019minlanishi kerak", "eng yuqori mehnat unumdorligiga erishish mehnatni ilmiy jihatdan tashkil etish va me\u2019yorlash, inson faoliyatidagi sun\u2019iy  va tabiiy cheklovlarni hisobga oluvchi mehnatkashni   dam olishning oqilona rejimi hisobidan ta\u2019minlanishi kerak ", "eng yuqori mehnat unumdorligiga erishish mehnatni ilmiy jihatdan tashkil etish va me\u2019yorlash, inson faoliyatidagi ma\u2019muriy cheklovlarni hisobga oluvchi intensiv mehnat qilishning oqilona rejimi hisobidan ta\u2019minlanishi kerak"], "correct": 1},
  {"question": "F.Teylor menejment sohasidagi ilmiy tadqiqotlarini qanday yo\u2019nalishga qaratdi?", "answers": ["F.Teylor menejment sohasidagi ilmiy tadqiqotlarini mehnat unumdorligini oshirish yo\u2019lida korxona xodimlari o\u2019rtasidagi ijtimoiy munosabatlarni o\u2019rganish va takomillashtirish yo\u2019nalishiga qaratdi", "F.Teylor menejment sohasidagi ilmiy tadqiqotlarini mehnat unumdorligini oshirish yo\u2019lida ish jarayonlarini ilmiy jihatdan tahlil etish va me\u2019yorlash yo\u2019nalishiga qaratdi", "F.Teylor menejment sohasidagi ilmiy tadqiqotlarini mehnat unumdorligini oshirish yo\u2019lida ish jarayonlarini ijtimoiy jihatdan tahlil etish va takomillashtirish yo\u2019nalishiga qaratdi", "F.Teylor menejment sohasidagi ilmiy tadqiqotlarini mehnat unumdorligini oshirish yo\u2019lida ish jarayonlarini texnologik jihatdan tahlil etish va ratsionalizatsiyalash yo\u2019nalishiga qaratdi"], "correct": 1},
  {"question": "F.Teylor menejerlarning qo\u2019l ostidagilar bilan munosabatlari chog\u2019ida qanday o\u2019zgarishlarni talab qildi va bu nima beradi?", "answers": ["F.Teylor menejerlarning qo\u2019l ostidagilar bilan munosabatlari chog\u2019ida avtoritar usullar va sub\u2019ektivizmni ilmiy qoidalar bilan almashtirishni talab qildi va bu ular o\u2019rtasida ishlab chiqarishda yuzaga keladigan nizolarni bartaraf etishini ta\u2019kidladi.", "F.Teylor menejerlarning qo\u2019l ostidagilar bilan munosabatlari chog\u2019ida demokratik usullar va ob\u2019ektivizmni ilmiy qoidalar bilan almashtirishni talab qildi va bu ular o\u2019rtasida ishlab chiqarishda yuzaga keladigan nizolarni bartaraf etishini ta\u2019kidladi.", "F.Teylor menejerlarning qo\u2019l ostidagilar bilan munosabatlari chog\u2019ida avtoritar usullar va sub\u2019ektivizmni huquqiy qoidalar bilan almashtirishni talab qildi va bu ular o\u2019rtasida ishlab chiqarishda yuzaga keladigan nizolarni bartaraf etishini ta\u2019kidladi.", "F.Teylor menejerlarning qo\u2019l ostidagilar bilan munosabatlari chog\u2019ida avtoritar usullar va ob\u2019ektivizmni ilmiy qoidalar bilan almashtirishni talab qildi va bu ular o\u2019rtasida ishlab chiqarishda yuzaga keladigan nizolarni aniqlashini ta\u2019kidladi."], "correct": 0},
  {"question": "Klassik yoki ma\u2019muriy boshqaruv maktabining asoschisi A.Fayol qanday nazariyani yaratdi?", "answers": ["klassik yoki ma\u2019muriy boshqaruv maktabining asoschisi, A.Fayol, tashkilotni boshqarish prinsiplari va funksiyalarini yaratdi. A.Fayol personal boshqaruv ob\u2019ekti, ishlab chiqilgan boshqaruv prinsiplarining tashkilotda amalga oshirilishi hamda menejerning yuksak shaxsiy va ahloqiy xususiyatlari personal xulqiga ta\u2019sir etishning asosi hisoblanadi, deb hisoblardi", "klassik yoki ma\u2019muriy boshqaruv maktabining asoschisi, A.Fayol, tashkilotni boshqarish prinsiplari va funksiyalarini yaratdi. A.Fayol personal boshqaruv sub\u2019ekti, ishlab chiqilgan boshqaruv prinsiplarining tashkilotda amalga oshirilishi hamda menejerning yuksak shaxsiy va ahloqiy xususiyatlari personal xulqiga ta\u2019sir etishning asosi hisoblanadi, deb hisoblardi", "klassik yoki ma\u2019muriy boshqaruv maktabining asoschisi, A.Fayol, tashkilotni boshqarish prinsiplari va strategiyalarini yaratdi. A.Fayol personal boshqaruv ob\u2019ekti, ishlab chiqilgan boshqaruv prinsiplarining tashkilotda amalga oshirilishi hamda menejerning yuksak shaxsiy va ahloqiy xususiyatlari personal xulqiga ta\u2019sir etishning asosi hisoblanadi, deb hisoblardi", "klassik yoki ma\u2019muriy boshqaruv maktabining asoschisi, A.Fayol, tashkilotni boshqarish strategiyalari va rejalarini yaratdi. A.Fayol personal boshqaruv ob\u2019ekti, ishlab chiqilgan boshqaruv strategiyalarining tashkilotda amalga oshirilishi hamda menejerning yuksak professional va ahloqiy xususiyatlari personal xulqiga ta\u2019sir etishning asosi hisoblanadi, deb hisoblardi"], "correct": 0},
  {"question": "Ma\u2019muriy boshqaruv maktabining rivojlanishida M.Veber qanday hissa qo\u2019shdi?", "answers": ["ma\u2019muriy boshqaruv maktabining rivojlanishida  tashkilotning byurokratik tuzilishi va uni boshqarish tizimi nazariyasini ishlab chiqqan germaniyalik sotsiolog M.Veber tashkilot huddi mashinadek ishlashi uchun menejer  har qanday vaziyatda o\u2019zini tutish tartib-qoidalari, har bir xodim huquq va majburiyatlarining ishlab chiqilishida ko\u2019rdi", "ma\u2019muriy boshqaruv maktabining rivojlanishida  tashkilotning byurokratik tuzilishi va uni boshqarish tizimi nazariyasini ishlab chiqqan ingliziyalik sotsiolog M.Veber tashkilot huddi mashinadek ishlashi uchun menejer  har qanday vaziyatda o\u2019zini tutish tartib-qoidalari, har bir xodim huquq va majburiyatlarining ishlab qilishida ko\u2019rdi", "ma\u2019muriy boshqaruv maktabining rivojlanishida  tashkilotning demokratik tuzilishi va uni boshqarish tizimi nazariyasini ishlab chiqqan germaniyalik sotsiolog M.Veber tashkilot huddi mashinadek ishlashi uchun menejer  har qanday vaziyatda o\u2019zini tutish tartib-qoidalari, har bir xodim huquq va majburiyatlarining ishlab chiqilishida ko\u2019rdi", "ma\u2019muriy boshqaruv maktabining rivojlanishida  tashkilotning byurokratik tuzilishi va uni boshqarish tizimi nazariyasini ishlab chiqqan germaniyalik iqtisodchi M.Veber tashkilot huddi mashinadek ishlashi uchun menejer  har qanday vaziyatda o\u2019zini tutish tartib-qoidalari, har bir xodim huquq va majburiyatlarining ishlab chiqilishida ko\u2019rdi"], "correct": 0},
  {"question": "E.Meyo insoniy munosabatlar maktabining asoschisi sifatida nima aniqladi?", "answers": ["E.Meyo (1880 \u2013 1949) insoniy munosabatlar maktabining asoschisi sifatida  xodimlar xulqiga, ularning mehnatga bo\u2019lgan munosabatiga jamoadagi ijtimoiy munosabatlar, guruhiy jarayonlar, rahbarlarning qo\u2019l ostidagilarga bo\u2019lgan munosabatining insoniyligi, jamoada ishlash kabi omillarning hal qiluvchi ta\u2019sirini aniqladi", "E.Meyo (1880 \u2013 1949) insoniy munosabatlar maktabining asoschisi sifatida  xodimlar xulqiga, ularning mehnatga bo\u2019lgan munosabatiga jamoadagi rasmiy munosabatlar, guruhiy jarayonlar, rahbarlarning qo\u2019l ostidagilarga bo\u2019lgan munosabatining insoniyligi, jamoada ishlash kabi omillarning hal qiluvchi ta\u2019sirini aniqladi", "E.Meyo (1880 \u2013 1949) insoniy munosabatlar maktabining asoschisi sifatida  xodimlar xulqiga, ularning mehnatga bo\u2019lgan munosabatiga jamoadagi ijtimoiy munosabatlar, individual jarayonlar, rahbarlarning qo\u2019l ostidagilarga bo\u2019lgan munosabatining insoniyligi, alohida ishlash kabi omillarning hal qiluvchi ta\u2019sirini aniqladi", "E.Meyo (1880 \u2013 1949) insoniy munosabatlar maktabining asoschisi sifatida  xodimlar xulqiga, ularning mehnatga bo\u2019lgan munosabatiga jamoadagi iqtisodiy munosabatlar, guruhiy jarayonlar, rahbarlarning qo\u2019l ostidagilarga bo\u2019lgan munosabatining insoniyligi, jamoada ishlash kabi omillarning hal qiluvchi ta\u2019sirini aniqladi"], "correct": 0},
  {"question": "A.Maslou ehtiyojlar ierarxik nazariyasi haqida gapirib bering.", "answers": ["XX asrning 40 \u2013 60-yillarida bixeviorist olimlar tomonidan ishlab chiqilgan motivatsiyaning bir necha nazariyalari insoniy munosabatlar maktabining rivojlanishiga turtki bergan  A.Maslouning  ehtiyojlar ierarxik nazariyasidir. Keyinchalik menejmentda keng qo\u2019llanilgan ushbu nazariya \u00abehtiyojlar piramidasi\u00bb sifatida ma\u2019lumdir", "XX asrning 40 \u2013 60-yillarida bixeviorist olimlar tomonidan ishlab chiqilgan motivatsiyaning bir necha nazariyalari insoniy munosabatlar maktabining rivojlanishiga turtki bergan  A.Maslouning  ehtiyojlar ierarxik nazariyasidir. Keyinchalik menejmentda qo\u2019llanilmagan ushbu nazariya \u00abehtiyojlar piramidasi\u00bb sifatida ma\u2019lumdir", "XX asrning 50 \u2013 70-yillarida bixeviorist olimlar tomonidan ishlab chiqilgan motivatsiyaning bir necha nazariyalari insoniy munosabatlar maktabining rivojlanishiga turtki bergan  A.Maslouning  ehtiyojlar ierarxik nazariyasidir. Keyinchalik menejmentda keng qo\u2019llanilgan ushbu nazariya \u00abehtiyojlar piramidasi\u00bb sifatida ma\u2019lumdir", "XX asrning 30 \u2013 50-yillarida bixeviorist olimlar tomonidan ishlab chiqilgan motivatsiyaning bir necha nazariyalari insoniy munosabatlar maktabining rivojlanishiga turtki bergan  A.Maslouning  ehtiyojlar ierarxik nazariyasidir. Keyinchalik menejmentda keng qo\u2019llanilgan ushbu nazariya \u00abehtiyojlar piramidasi\u00bb sifatida ma\u2019lumdir"], "correct": 0},
  {"question": "Xulq-atvorchilik yo\u2019nalishi vakillari shaxsni nima sifatida ko\u2019rdilar?", "answers": ["xulq-atvorchilik yo\u2019nalishi vakillari shaxsni ijtimoiy munosabatlarning mahsuli sifatida ko\u2019rdilar; ularning fikriga ko\u2019ra, shaxsning xulqi tashqi muhit (oila, ijtimoiy guruh, tashkilot) ta\u2019siri ostida shakllanadi; shaxsga nisbatan boshqarish uchun uning xulq namoyon bo\u2019lishining xilma-xil jihatlarini o\u2019rganish asosida yondashadilar", "xulq-atvorchilik yo\u2019nalishi vakillari shaxsni biologik munosabatlarning mahsuli sifatida ko\u2019rdilar; ularning fikriga ko\u2019ra, shaxsning xulqi tashqi muhit ta\u2019siri ostida shakllanadi; shaxsga nisbatan boshqarish uchun uning xulq namoyon bo\u2019lishining xilma-xil jihatlarini o\u2019rganish asosida yondashadilar", "xulq-atvorchilik yo\u2019nalishi vakillari shaxsni iqtisodiy munosabatlarning mahsuli sifatida ko\u2019rdilar; ularning fikriga ko\u2019ra, shaxsning xulqi ichki muhit ta\u2019siri ostida shakllanadi; shaxsga nisbatan boshqarish uchun uning xulq namoyon bo\u2019lishining iqtisodiy jihatlarini o\u2019rganish asosida yondashadilar", "xulq-atvorchilik yo\u2019nalishi vakillari shaxsni ijtimoiy munosabatlarning mahsuli sifatida ko\u2019rdilar; ularning fikriga ko\u2019ra, shaxsning xulqi ichki muhit ta\u2019siri ostida shakllanadi; shaxsga nisbatan boshqarish uchun uning xulq namoyon bo\u2019lishining xilma-xil jihatlarini o\u2019rganish asosida yondashadilar"], "correct": 0},
  {"question": "Tizimli yondashuv maktabi vakillari tashkilotni nima deb hisoblashadi?", "answers": ["tizimli yondashuv maktabi vakillari tashkilotni bir-biri bilan o\u2019zaro aloqada bo\u2019lgan elementlardan iborat yaxlit tizim, deb hisoblashadi. Bunda tashkilotning tashqi va ichki muhiti o\u2019rtasidagi o\u2019zaro munosabat va ta\u2019sirga alohida e\u2019tibor qaratiladi", "tizimli yondashuv maktabi vakillari tashkilotni bir-biri bilan o\u2019zaro aloqada bo\u2019lmagan elementlardan iborat yaxlit tizim, deb hisoblashadi. Bunda tashkilotning tashqi va ichki muhiti o\u2019rtasidagi o\u2019zaro munosabat va ta\u2019sirga alohida e\u2019tibor qaratiladi", "tizimli yondashuv maktabi vakillari tashkilotni bir-biri bilan o\u2019zaro aloqada bo\u2019lgan elementlardan iborat yaxlit tizim, deb hisoblashadi. Bunda tashkilotning faqat ichki muhiti o\u2019zaro munosabat va ta\u2019siriga alohida e\u2019tibor qaratiladi", "tizimli yondashuv maktabi vakillari tashkilotni bir-biri bilan o\u2019zaro aloqada bo\u2019lgan bo\u2019limlardan iborat qisman tizim, deb hisoblashadi. Bunda tashkilotning tashqi va ichki muhiti o\u2019rtasidagi o\u2019zaro munosabat va ta\u2019sirga alohida e\u2019tibor qaratiladi"], "correct": 0},
  {"question": "Vaziyatga qarab boshqarish maktabining mohiyati nimadan iborat?", "answers": ["vaziyatga qarab boshqarish maktabining mohiyati shundaki, boshqaruvning yagona usullari yo\u2019q, boshqarish usullar va yo\u2019llar to\u2019plamidan vaziyatga qarab tanlash  kerak", "vaziyatga qarab boshqarish maktabining mohiyati shundaki, boshqaruvning universal usullari bor, ularni vaziyatga qarab qo\u2019llash  kerak", "vaziyatga qarab boshqarish maktabining mohiyati shundaki, boshqaruvning yagona usullari yo\u2019q, boshqarish usullar va yo\u2019llar to\u2019plamidan vaziyatga qarab emas, balki amaliyot asosida tanlash  kerak", "vaziyatga qarab boshqarish maktabining mohiyati shundaki, boshqaruvda universal usullar yagona va ular vaziyatga bog\u2019liq emas"], "correct": 0},
  {"question": "Tashkiliy xulqning asosiy xususiyatlariga nimalar kiradi?", "answers": ["tashkiliy xulqning asosiy xususiyatlariga quyidagilar kiradi: umumiylik; rasmiylik; ilmiylik; axborotga yo\u2019naltirilganlik; aniqlik va amaliyot bilan bog\u2019liqlik; ko\u2019p darajalilik; ochiqlik", "tashkiliy xulqning asosiy xususiyatlariga quyidagilar kiradi: umumiylik; rasmiylik; ilmiylik; axborotga yo\u2019naltirilganlik; aniqlik va amaliyot bilan bog\u2019liqlik; ko\u2019p darajalilik", "tashkiliy xulqning asosiy xususiyatlariga quyidagilar kiradi: xususiylik; rasmiylik; ilmiylik; axborotga yo\u2019naltirilganlik; aniqlik va amaliyot bilan bog\u2019liqlik; ko\u2019p darajalilik; ochiqlik", "tashkiliy xulqning asosiy xususiyatlariga quyidagilar kiradi: umumiylik; norasmiylik; ilmiylik; axborotga yo\u2019naltirilganlik; aniqlik va amaliyot bilan bog\u2019liqlik; ko\u2019p darajalilik; ochiqlik"], "correct": 0},
  {"question": "Tashkiliy xulq fanining metodologiyasi nimadan iborat?", "answers": ["tashkiliy xulq fanining metodologiyasi quyidagilardan iborat: tadqiqot ob\u2019ektini aniqlash; tadqiqot usullarini tanlash; tadqiqotni o\u2019tkazish; natijalarni tahlil qilish va xulosalar chiqarish", "tashkiliy xulq fanining metodologiyasi quyidagilardan iborat: tadqiqot sub\u2019ektini aniqlash; tadqiqot usullarini tanlash; tadqiqotni o\u2019tkazish; natijalarni tahlil qilish va xulosalar chiqarish", "tashkiliy xulq fanining metodologiyasi quyidagilardan iborat: tadqiqot ob\u2019ektini aniqlash; tadqiqot usullarini tanlash; tadqiqotni o\u2019tkazmasdan; natijalarni taxmin qilish va xulosalar chiqarish", "tashkiliy xulq fanining metodologiyasi quyidagilardan iborat: tadqiqot ob\u2019ektini aniqlash; tadqiqot usullarini belgilash; tadqiqotni o\u2019tkazish; natijalarni tahlil qilmasdan xulosalar chiqarish"], "correct": 0},
  {"question": "Shaxs tushunchasi nimani anglatadi?", "answers": ["shaxs tushunchasi muayyan ijtimoiy munosabatlar tizimida o\u2019z o\u2019rniga ega bo\u2019lgan, ongli faoliyat ko\u2019rsatuvchi, ijtimoiy munosabatlarning sub\u2019ekti va ob\u2019ekti bo\u2019lgan insonni anglatadi", "shaxs tushunchasi muayyan biologik xususiyatlarga ega bo\u2019lgan, ongli faoliyat ko\u2019rsatuvchi, ijtimoiy munosabatlarning sub\u2019ekti va ob\u2019ekti bo\u2019lgan insonni anglatadi", "shaxs tushunchasi muayyan ijtimoiy munosabatlar tizimida o\u2019z o\u2019rniga ega bo\u2019lgan, ongsiz faoliyat ko\u2019rsatuvchi, ijtimoiy munosabatlarning sub\u2019ekti va ob\u2019ekti bo\u2019lgan insonni anglatadi", "shaxs tushunchasi muayyan iqtisodiy munosabatlar tizimida o\u2019z o\u2019rniga ega bo\u2019lgan, ongli faoliyat ko\u2019rsatuvchi, iqtisodiy munosabatlarning sub\u2019ekti va ob\u2019ekti bo\u2019lgan insonni anglatadi"], "correct": 0},
  {"question": "Shaxsning asosiy xususiyatlariga nimalar kiradi?", "answers": ["shaxsning asosiy xususiyatlariga quyidagilar kiradi: individual xususiyatlar; qobiliyatlar; idrok; munosabat va qadriyatlar; ehtiyojlar", "shaxsning asosiy xususiyatlariga quyidagilar kiradi: biologik xususiyatlar; qobiliyatlar; idrok; munosabat va qadriyatlar; ehtiyojlar", "shaxsning asosiy xususiyatlariga quyidagilar kiradi: individual xususiyatlar; ko\u2019nikmalar; idrok; munosabat va qadriyatlar; ehtiyojlar", "shaxsning asosiy xususiyatlariga quyidagilar kiradi: individual xususiyatlar; qobiliyatlar; idrok; munosabat va maqsadlar; ehtiyojlar"], "correct": 0},
  {"question": "Qobiliyat nima?", "answers": ["qobiliyat - bu insonning biror ishni muvaffaqiyatli bajarish imkonini beruvchi xususiyatlari majmuidir", "qobiliyat - bu insonning biror ishni bajarish uchun zarur bo\u2019lgan bilimlar majmuidir", "qobiliyat - bu insonning biror ishni bajarish uchun zarur bo\u2019lgan ko\u2019nikmalar majmuidir", "qobiliyat - bu insonning biror ishni bajarish uchun zarur bo\u2019lgan tajriba majmuidir"], "correct": 0},
  {"question": "Idrok nima va u qanday ahamiyatga ega?", "answers": ["idrok - bu insonning atrofdagi dunyoni his-tuyg\u2019ulari orqali anglash jarayonidir; u insonning xulqiga bevosita ta\u2019sir ko\u2019rsatadi", "idrok - bu insonning atrofdagi dunyoni aql orqali anglash jarayonidir; u insonning bilimiga bevosita ta\u2019sir ko\u2019rsatadi", "idrok - bu insonning atrofdagi dunyoni his-tuyg\u2019ulari orqali anglash jarayonidir; u insonning bilimiga bevosita ta\u2019sir ko\u2019rsatadi", "idrok - bu insonning atrofdagi dunyoni aql orqali anglash jarayonidir; u insonning xulqiga bevosita ta\u2019sir ko\u2019rsatadi"], "correct": 0},
  {"question": "Munosabat va qadriyatlar shaxs xulqiga qanday ta\u2019sir ko\u2019rsatadi?", "answers": ["munosabat va qadriyatlar shaxsning xulqini bevosita belgilab beradi; ular insonning nimani yaxshi ko\u2019rishi, nimani qadrlaши va qanday yo\u2019l tutishini aniqlab beradi", "munosabat va qadriyatlar shaxsning xulqiga bilvosita ta\u2019sir ko\u2019rsatadi; ular insonning nimani yaxshi ko\u2019rishi, nimani qadrlaши va qanday yo\u2019l tutishini aniqlab bermaydi", "munosabat va qadriyatlar shaxsning xulqini faqat tashqi muhit orqali belgilab beradi; ular insonning nimani yaxshi ko\u2019rishi va nimani qadrlaши ni aniqlab beradi", "munosabat va qadriyatlar shaxsning xulqiga ta\u2019sir ko\u2019rsatmaydi; ular faqat insonning bilimini belgilab beradi"], "correct": 0},
  {"question": "Ehtiyojlar motivatsiya jarayonida qanday rol o\u2019ynaydi?", "answers": ["ehtiyojlar motivatsiya jarayonida asosiy rol o\u2019ynaydi; ular insonni harakatga undovchi kuch bo\u2019lib xizmat qiladi", "ehtiyojlar motivatsiya jarayonida ikkinchi darajali rol o\u2019ynaydi; ular insonni harakatga undovchi kuch bo\u2019lib xizmat qilmaydi", "ehtiyojlar motivatsiya jarayonida hech qanday rol o\u2019ynamaydi; ular faqat insonning biologik holati bilan bog\u2019liq", "ehtiyojlar motivatsiya jarayonida yordamchi rol o\u2019ynaydi; ular insonni harakatdan to\u2019xtatuvchi kuch bo\u2019lib xizmat qiladi"], "correct": 0},
  {"question": "Motivatsiya nima va u qanday jarayon?", "answers": ["motivatsiya - bu insonni ma\u2019lum maqsad sari yo\u2019naltirilgan faoliyatga undovchi ichki va tashqi omillar majmui hamda jarayonidir", "motivatsiya - bu insonni ma\u2019lum maqsad sari yo\u2019naltirilgan faoliyatdan to\u2019xtatuvchi ichki va tashqi omillar majmui hamda jarayonidir", "motivatsiya - bu insonni ma\u2019lum maqsad sari yo\u2019naltirilgan faoliyatga undovchi faqat ichki omillar majmui hamda jarayonidir", "motivatsiya - bu insonni ma\u2019lum maqsad sari yo\u2019naltirilgan faoliyatga undovchi faqat tashqi omillar majmui hamda jarayonidir"], "correct": 0},
  {"question": "Motivatsiyaning mazmuniy nazariyalari nimani o\u2019rganadi?", "answers": ["motivatsiyaning mazmuniy nazariyalari insonni harakatga undovchi ehtiyojlar va omillarni o\u2019rganadi", "motivatsiyaning mazmuniy nazariyalari insonni harakatga undovchi jarayon va mexanizmlarni o\u2019rganadi", "motivatsiyaning mazmuniy nazariyalari insonni harakatga undovchi tashqi omillar va mukofotlarni o\u2019rganadi", "motivatsiyaning mazmuniy nazariyalari insonni harakatga undovchi biologik omillar va instinktlarni o\u2019rganadi"], "correct": 0},
  {"question": "Motivatsiyaning jarayoniy nazariyalari nimani o\u2019rganadi?", "answers": ["motivatsiyaning jarayoniy nazariyalari insonni harakatga undovchi jarayon va mexanizmlarni, ya\u2019ni insonning o\u2019z xulqini qanday boshqarishini o\u2019rganadi", "motivatsiyaning jarayoniy nazariyalari insonni harakatga undovchi ehtiyojlar va omillarni o\u2019rganadi", "motivatsiyaning jarayoniy nazariyalari insonni harakatga undovchi tashqi omillar va jazo tizimini o\u2019rganadi", "motivatsiyaning jarayoniy nazariyalari insonni harakatga undovchi biologik omillar va instinktlarni o\u2019rganadi"], "correct": 0},
  {"question": "A.Maslou ehtiyojlar ierarxiyasini qanday darajalarga bo\u2019ldi?", "answers": ["A.Maslou ehtiyojlar ierarxiyasini 5 darajaga bo\u2019ldi: fiziologik ehtiyojlar; xavfsizlik ehtiyojlari; ijtimoiy ehtiyojlar; hurmat ehtiyojlari; o\u2019z-o\u2019zini namoyon etish ehtiyojlari", "A.Maslou ehtiyojlar ierarxiyasini 4 darajaga bo\u2019ldi: fiziologik ehtiyojlar; xavfsizlik ehtiyojlari; ijtimoiy ehtiyojlar; o\u2019z-o\u2019zini namoyon etish ehtiyojlari", "A.Maslou ehtiyojlar ierarxiyasini 3 darajaga bo\u2019ldi: birlamchi ehtiyojlar; ikkilamchi ehtiyojlar; yuqori darajali ehtiyojlar", "A.Maslou ehtiyojlar ierarxiyasini 6 darajaga bo\u2019ldi: biologik ehtiyojlar; xavfsizlik ehtiyojlari; ijtimoiy ehtiyojlar; hurmat ehtiyojlari; bilish ehtiyojlari; o\u2019z-o\u2019zini namoyon etish ehtiyojlari"], "correct": 0},
  {"question": "F.Gersbergning ikki omilli nazariyasi haqida gapirib bering.", "answers": ["F.Gersbergning ikki omilli nazariyasiga ko\u2019ra, mehnat jarayonida ikkita omil guruhini ajratish mumkin: gigienik omillar (mehnat sharoiti, ish haqi, munosabatlar) va motivatorlar (muvaffaqiyat, tan olinish, mas\u2019uliyat, o\u2019sish imkoniyati)", "F.Gersbergning ikki omilli nazariyasiga ko\u2019ra, mehnat jarayonida ikkita omil guruhini ajratish mumkin: tashqi omillar va ichki omillar; tashqi omillar qoniqishni ta\u2019minlaydi, ichki omillar esa norozilikni keltirib chiqaradi", "F.Gersbergning ikki omilli nazariyasiga ko\u2019ra, mehnat jarayonida ikkita omil guruhini ajratish mumkin: birlamchi omillar va ikkilamchi omillar; birlamchi omillar motivatsiyani ta\u2019minlaydi, ikkilamchi omillar esa ta\u2019minlamaydi", "F.Gersbergning ikki omilli nazariyasiga ko\u2019ra, mehnat jarayonida uchta omil guruhini ajratish mumkin: gigienik omillar, motivatorlar va neytral omillar"], "correct": 0},
  {"question": "D.Makgregorning X va Y nazariyalari haqida gapirib bering.", "answers": ["D.Makgregorning X nazariyasiga ko\u2019ra, odamlar ishni yoqtirmaydi va majburlanmasa ishlamaydi; Y nazariyasiga ko\u2019ra esa, odamlar ishni tabiiy holat sifatida qabul qiladi va o\u2019z-o\u2019zini boshqara oladi", "D.Makgregorning X nazariyasiga ko\u2019ra, odamlar ishni yaxshi ko\u2019radi va o\u2019z-o\u2019zini boshqara oladi; Y nazariyasiga ko\u2019ra esa, odamlar ishni yoqtirmaydi va majburlanmasa ishlamaydi", "D.Makgregorning X va Y nazariyalari bir xil bo\u2019lib, odamlar ishni tabiiy holat sifatida qabul qiladi, degan g\u2019oyaga asoslanadi", "D.Makgregorning X nazariyasiga ko\u2019ra, odamlar faqat moddiy rag\u2019bat uchun ishlaydi; Y nazariyasiga ko\u2019ra esa, odamlar faqat ma\u2019naviy rag\u2019bat uchun ishlaydi"], "correct": 0},
  {"question": "Guruh nima va u qanday turlarga bo\u2019linadi?", "answers": ["guruh - bu umumiy maqsad, manfaat yoki faoliyat asosida birlashgan ikki va undan ortiq kishilar yig\u2019indisi; guruhlar rasmiy va norasmiy turlarga bo\u2019linadi", "guruh - bu umumiy maqsad, manfaat yoki faoliyat asosida birlashgan uch va undan ortiq kishilar yig\u2019indisi; guruhlar rasmiy va norasmiy turlarga bo\u2019linadi", "guruh - bu umumiy maqsad, manfaat yoki faoliyat asosida birlashgan ikki va undan ortiq kishilar yig\u2019indisi; guruhlar faqat rasmiy turga bo\u2019linadi", "guruh - bu umumiy hududda yashovchi kishilar yig\u2019indisi; guruhlar rasmiy va norasmiy turlarga bo\u2019linadi"], "correct": 0},
  {"question": "Rasmiy guruhlar qanday tashkil topadi?", "answers": ["rasmiy guruhlar tashkilot tomonidan ma\u2019lum maqsadlarni amalga oshirish uchun maxsus tuziladi; ularning tuzilishi, vazifalari va a\u2019zoligi rasmiylashtirilgan bo\u2019ladi", "rasmiy guruhlar o\u2019z-o\u2019zidan, a\u2019zolarning umumiy manfaatlari asosida tashkil topadi; ularning tuzilishi rasmiylashtirilmagan bo\u2019ladi", "rasmiy guruhlar faqat davlat tashkilotlarida tashkil topadi; ularning tuzilishi, vazifalari va a\u2019zoligi rasmiylashtirilgan bo\u2019ladi", "rasmiy guruhlar faqat xususiy tashkilotlarda tashkil topadi; ularning tuzilishi rasmiylashtirilgan bo\u2019ladi"], "correct": 0},
  {"question": "Norasmiy guruhlar qanday xususiyatlarga ega?", "answers": ["norasmiy guruhlar o\u2019z-o\u2019zidan, a\u2019zolarning umumiy manfaatlari, do\u2019stlik yoki yaqinlik asosida tashkil topadi; ularning rasmiy tuzilishi yo\u2019q, ammo o\u2019ziga xos me\u2019yorlari va rahbarlari bor", "norasmiy guruhlar tashkilot tomonidan maxsus tuziladi; ularning rasmiy tuzilishi bor, ammo vazifalari rasmiylashtirilmagan", "norasmiy guruhlar faqat yosh xodimlar orasida tashkil topadi; ularning rasmiy tuzilishi yo\u2019q va rahbarlari ham yo\u2019q", "norasmiy guruhlar faqat katta yoshli xodimlar orasida tashkil topadi; ularning o\u2019ziga xos me\u2019yorlari yo\u2019q"], "correct": 0},
  {"question": "Jamoaning guruhdan farqi nimada?", "answers": ["jamoa guruhdan farqli o\u2019laroq, a\u2019zolari birgalikda ishlaydi, o\u2019zaro bog\u2019liq vazifalarga ega bo\u2019ladi va umumiy natijaga mas\u2019uliyat his qiladi", "jamoa guruhdan farq qilmaydi; ular bir xil tushunchalardir", "jamoa guruhdan farqli o\u2019laroq, faqat rasmiy tashkilotlarda bo\u2019ladi va yuqori rahbarlik tomonidan tayinlanadi", "jamoa guruhdan farqli o\u2019laroq, kamroq kishilardan iborat bo\u2019ladi va maxsus vazifalarni bajaradi"], "correct": 0},
  {"question": "Rahbarlik va liderlik o\u2019rtasidagi farq nimada?", "answers": ["rahbarlik rasmiy lavozim va vakolat bilan bog\u2019liq bo\u2019lsa, liderlik shaxsning ta\u2019sir ko\u2019rsatish qobiliyati va boshqalarni ergashtira olishi bilan belgilanadi", "rahbarlik va liderlik bir xil tushunchalar bo\u2019lib, ular o\u2019rtasida farq yo\u2019q", "rahbarlik liderlikdan yuqori bo\u2019lib, faqat rasmiy tashkilotlarda bo\u2019ladi", "liderlik rahbarlikdan yuqori bo\u2019lib, faqat norasmiy guruhlarda bo\u2019ladi"], "correct": 0},
  {"question": "Liderlik uslublari qanday turlarga bo\u2019linadi?", "answers": ["liderlik uslublari avtoritar, demokratik va liberal (erkin) uslublarga bo\u2019linadi", "liderlik uslublari faqat avtoritar va demokratik uslublarga bo\u2019linadi", "liderlik uslublari rasmiy va norasmiy uslublarga bo\u2019linadi", "liderlik uslublari qat\u2019iy va yumshoq uslublarga bo\u2019linadi"], "correct": 0},
  {"question": "Avtoritar liderlik uslubining xususiyatlari nimalardan iborat?", "answers": ["avtoritar liderlik uslubida barcha qarorlar rahbar tomonidan yolg\u2019iz qabul qilinadi; xodimlarga ko\u2019rsatma va buyruqlar beriladi; nazorat qat\u2019iy amalga oshiriladi", "avtoritar liderlik uslubida qarorlar jamoa tomonidan birgalikda qabul qilinadi; xodimlarga erkinlik beriladi; nazorat yumshoq amalga oshiriladi", "avtoritar liderlik uslubida rahbar qarorlarni xodimlar bilan maslahatlashib qabul qiladi; xodimlarga ma\u2019lum darajada erkinlik beriladi", "avtoritar liderlik uslubida xodimlar barcha qarorlarni o\u2019zlari qabul qiladi; rahbar faqat umumiy yo\u2019nalish beradi"], "correct": 0},
  {"question": "Demokratik liderlik uslubining xususiyatlari nimalardan iborat?", "answers": ["demokratik liderlik uslubida rahbar qarorlarni xodimlar bilan maslahatlashib qabul qiladi; xodimlarning fikri hisobga olinadi; nazorat o\u2019rtacha darajada amalga oshiriladi", "demokratik liderlik uslubida barcha qarorlar rahbar tomonidan yolg\u2019iz qabul qilinadi; xodimlarga buyruqlar beriladi", "demokratik liderlik uslubida xodimlar barcha qarorlarni o\u2019zlari qabul qiladi; rahbar hech qanday nazorat qilmaydi", "demokratik liderlik uslubida qarorlar faqat yuqori rahbariyat tomonidan qabul qilinadi; xodimlarning fikri hisobga olinmaydi"], "correct": 0},
  {"question": "Kommunikatsiya nima va u tashkilotda qanday ahamiyatga ega?", "answers": ["kommunikatsiya - bu ma\u2019lumot almashish jarayoni bo\u2019lib, tashkilotda muvofiqlashtirish, qaror qabul qilish va xodimlar o\u2019rtasidagi hamkorlikni ta\u2019minlashda muhim ahamiyatga ega", "kommunikatsiya - bu faqat og\u2019zaki muloqot bo\u2019lib, tashkilotda ikkinchi darajali ahamiyatga ega", "kommunikatsiya - bu faqat yozma muloqot bo\u2019lib, tashkilotda rasmiy hujjatlar almashish uchun ishlatiladi", "kommunikatsiya - bu faqat elektron muloqot bo\u2019lib, zamonaviy tashkilotlarda asosiy muloqot shaklidir"], "correct": 0},
  {"question": "Kommunikatsiya jarayonining asosiy bosqichlari qanday?", "answers": ["kommunikatsiya jarayonining asosiy bosqichlari: jo\u2019natuvchi - kodlash - kanal - dekodlash - qabul qiluvchi - teskari aloqa", "kommunikatsiya jarayonining asosiy bosqichlari: jo\u2019natuvchi - kanal - qabul qiluvchi", "kommunikatsiya jarayonining asosiy bosqichlari: ma\u2019lumot - uzatish - qabul qilish", "kommunikatsiya jarayonining asosiy bosqichlari: kodlash - uzatish - dekodlash"], "correct": 0},
  {"question": "Tashkiliy kommunikatsiyaning to\u2019siqlari qanday turlarga bo\u2019linadi?", "answers": ["tashkiliy kommunikatsiya to\u2019siqlari shaxsiy (til, idrok, his-tuyg\u2019u) va tashkiliy (ierarxiya, axborot haddan tashqari ko\u2019pligi, filtratsiya) turlarga bo\u2019linadi", "tashkiliy kommunikatsiya to\u2019siqlari faqat texnik turlarga bo\u2019linadi", "tashkiliy kommunikatsiya to\u2019siqlari faqat shaxsiy turlarga bo\u2019linadi", "tashkiliy kommunikatsiya to\u2019siqlari rasmiy va norasmiy turlarga bo\u2019linadi"], "correct": 0},
  {"question": "Qaror qabul qilish jarayoni qanday bosqichlardan iborat?", "answers": ["qaror qabul qilish jarayoni: muammoni aniqlash, mezonlarni belgilash, muqobillarni ishlab chiqish, baholash, tanlash va amalga oshirish bosqichlaridan iborat", "qaror qabul qilish jarayoni faqat muammoni aniqlash va yechim topishdan iborat", "qaror qabul qilish jarayoni: muammoni aniqlash va eng yaxshi yechimni tanlashdan iborat", "qaror qabul qilish jarayoni: ma\u2019lumot to\u2019plash va qaror qabul qilishdan iborat"], "correct": 0},
  {"question": "Tashkiliy madaniyat nima?", "answers": ["tashkiliy madaniyat - bu tashkilot a\u2019zolari tomonidan qabul qilingan umumiy qadriyatlar, me\u2019yorlar, e\u2019tiqodlar va xulq-atvor tartiblari majmuidir", "tashkiliy madaniyat - bu tashkilotning binosi va jihozlari ko\u2019rinishidagi moddiy muhitidir", "tashkiliy madaniyat - bu tashkilotning rasmiy qoidalar va ko\u2019rsatmalar to\u2019plamidir", "tashkiliy madaniyat - bu tashkilot rahbarlarining shaxsiy qadriyatlari va e\u2019tiqodlaridir"], "correct": 0},
  {"question": "Tashkiliy madaniyatning asosiy elementlariga nimalar kiradi?", "answers": ["tashkiliy madaniyatning asosiy elementlariga: qadriyatlar, me\u2019yorlar, marosimlar, ramzlar, qahramonlar va hikoyalar kiradi", "tashkiliy madaniyatning asosiy elementlariga faqat rasmiy qoidalar va tartiblar kiradi", "tashkiliy madaniyatning asosiy elementlariga faqat moddiy ashyolar va binolar kiradi", "tashkiliy madaniyatning asosiy elementlariga faqat xodimlarning yoshi va tajribasi kiradi"], "correct": 0},
  {"question": "O\u2019zgarishlarni boshqarish nima uchun muhim?", "answers": ["o\u2019zgarishlarni boshqarish tashkilotning yangi sharoitlarga moslashishi, raqobatbardoshligini saqlashi va rivojlanishi uchun muhimdir", "o\u2019zgarishlarni boshqarish faqat inqirozli vaziyatlarda muhim bo\u2019ladi", "o\u2019zgarishlarni boshqarish faqat yirik tashkilotlar uchun muhim bo\u2019ladi", "o\u2019zgarishlarni boshqarish faqat rahbarlar uchun muhim bo\u2019lib, oddiy xodimlar uchun ahamiyatsiz"], "correct": 0},
  {"question": "Nizo nima va u qanday turlarga bo\u2019linadi?", "answers": ["nizo - bu ikki yoki undan ortiq tomonlar o\u2019rtasidagi kelishmovchilik yoki ziddiyat; nizolar shaxs ichidagi, shaxslararo, guruh ichidagi va guruhlararo turlarga bo\u2019linadi", "nizo - bu ikki tomonning o\u2019rtasidagi kelishmovchilik; nizolar faqat shaxslararo va guruhlararo turlarga bo\u2019linadi", "nizo - bu har qanday muloqotdagi kelishmovchilik; nizolar faqat ijobiy va salbiy turlarga bo\u2019linadi", "nizo - bu faqat ish jarayonidagi kelishmovchilik; nizolar rasmiy va norasmiy turlarga bo\u2019linadi"], "correct": 0},
  {"question": "Nizolarni hal etishning asosiy usullariga nimalar kiradi?", "answers": ["nizolarni hal etishning asosiy usullari: hamkorlik, murosaga kelish, raqobat, muammoni chetlab o\u2019tish va moslashish", "nizolarni hal etishning asosiy usullari faqat murosaga kelish va raqobatdan iborat", "nizolarni hal etishning asosiy usullari faqat yuqori rahbariyat qaroriga bo\u2019ysunishdan iborat", "nizolarni hal etishning asosiy usullari faqat sud orqali hal qilishdan iborat"], "correct": 0},
  {"question": "Shaxslararo nizolarni boshqarish usullariga qaysi usullar kiradi?", "answers": ["o\u2019zini chetga olish usuli; silliqlash usuli; ishontirish usuli; majburlash usuli; bitimga kelish usuli", "o\u2019zini chetga olish usuli; kelishtirish usuli; ishontirish usuli; majburlash usuli; bitimga kelish usuli", "o\u2019zini chetga olish usuli; kelishtirish usuli; konsensus usuli; majburlash usuli; bitimga kelish usuli", "o\u2019zini chetga olish usuli; kelishtirish usuli; konsensus usuli; majburlash usuli; bir tomon talabini qondirish"], "correct": 0},
  {"question": "Nizolarni boshqarish qanaqa xususiyatga ega bo\u2019lishi mumkin?", "answers": ["yakka tartibli (shaxsga oid yondashishlar); rasmiy (ishlab chiqilgan yo\u2019riqnomalar, nizomlar atrofidagi); ijtimoiy (guruhlarning ijtimoiy ahvoli hisobga olingan);yuridik(harakatlar qonunlar doirasida amalga oshiriladigan)", "yakka tartibli (shaxsga oid yondashishlar);norasmiy (ishlab chiqilgan yo\u2019riqnomalar, nizomlar atrofidagi);ijtimoiy (guruhlarning ijtimoiy ahvoli hisobga olmasdan); yuridik(harakatlar qonunlar doirasida amalga oshiriladigan)", "yakka tartibli (shaxsga oid yondashishlar);norasmiy ( kasaba uyushmasi ishlab chiqqan yo\u2019riqnomalar, nizomlar atrofidagi); demokratik (guruhlarning ijtimoiy ahvoli hisobga olingan);yuridik(harakatlar qonunlar doirasida amalga oshiriladigan)", "yakka tartibli (shaxsga oid yondashishlar);norasmiy (jamoatchilik ishlab chiqqan yo\u2019riqnomalar, nizomlar atrofidagi); demokratik (guruhlarning ijtimoiy ahvoli hisobga olingan); huquqiy (korxona qonunlari doirasida amalga oshiriladigan)"], "correct": 0},
  {"question": "Stress qanday atama?", "answers": ["stress (ing.stress-bosim, tazyiq,, zo\u2019riqish, tabiiy asabiy tus olish)-turli ekstremal ta\u2019sirlarga javoban qo\u2019zg\u2019aladigan, inson ahvoli (holati)ni atroflicha anglatish uchun qo\u2019llanadigan atama", "stress (ing.stress-bosim, tazyiq,, zo\u2019riqish, g\u2019ayritabiiy asabiy tus olish)-turli ekstremal ta\u2019sirlarga javoban qo\u2019zg\u2019aladigan, inson ahvoli (holati)ni atroflicha anglatish uchun qo\u2019llanadigan atama", "stress (ing.stress-bosim, tazyiq,, zo\u2019riqish, tabiiy asabiy tus olish)-turli ekstremistlar ta\u2019sirlarga javoban qo\u2019zg\u2019aladigan, inson ahvoli (holati)ni atroflicha anglatish uchun qo\u2019llanadigan atama", "stress (ing.stress-bosim, tazyiq,, zo\u2019riqish, tabiiy asabiy tus olish)-turli ekstremal (mustasno) ta\u2019sirlarga javoban qo\u2019zg\u2019aladigan, inson ahvoli (holati)ni atroflicha anglatish uchun qo\u2019llanadigan atama"], "correct": 1},
  {"question": "Stress qanday vujudga keladi?", "answers": ["stress: shaxsiy hayotda ham, har bir kasbda ham-hamma erda bor( bo\u2019lib turadi). Biroq, aslida, u mehnat qilishdan emas, balki, ish bajariladigan u yoki bu sharoitlardan yoxud holatlardan, u ro\u2019y berayotgan vaziyatda ilojsizlikni his etishdan kelib chiqadi", "stress: shaxsiy hayotda ham, har bir kasbda ham-hamma erda bor", "stress: shaxsiy hayotda ham, har bir kasbda ham-hamma erda bor. Ammo, u mehnat qilishdan, ish bajariladigan usullardan u yoki bu sharoitlardan yoxud holatlarda vaziyat ta\u2019siridan qatiy nazar ilojsizlikni his etishdan kelib chiqadi", "stress: shaxsiy hayotda ham, har bir kasbda ham-hamma erda bor(bo\u2019lib turadi). Biroq, aslida, u mehnat qilishdan, ish bajariladigan usullardan u yoki bu sharoitlardan yoxud holatlarda ro\u2019yi beradigan vaziyatda ilojini topganda ham  o\u2019zini noto\u2019g\u2019ri  his etishdan kelib chiqadi"], "correct": 0},
  {"question": "Stress inson organizmini noxush o\u2019zgarishlarga olib keladimi?", "answers": ["tadqiqotlardan aniqlanishicha, stress inson organizmini noxush o\u2019zgarishlarga olib keladi, buning natijasida psixikada ham buzilishlar (o\u2019zgarishlar) ro\u2019y beradi; odamlar faol hayot tarzidan bosh tortib, o\u2019z yog\u2019lariga o\u2019zlari qovuriladilar (ich-etlarini eydilar); inson axloqning fiziologik holatini og\u2019irlashtiradi", "tadqiqotlardan aniqlanishicha, stress inson organizmini noxush o\u2019zgarishlarga olib keladi, buning natijasida psixikadan mustasno  buzilishlar (o\u2019zgarishlar) ro\u2019y beradi; odamlar faol hayot tarzidan bosh tortib, o\u2019z yog\u2019lariga o\u2019zlari qovuriladilar (ich-etlarini eydilar);inson axloqning fiziologik holatini og\u2019irlashtiradi", "tadqiqotlardan aniqlanishicha, stress inson organizmini noxush o\u2019zgarishlarga olib keladi, buning natijasida psixikadan mustasno  buzilishlar (o\u2019zgarishlar) ro\u2019y beradi; odamlar faol hayot tarzidan bosh tortib, o\u2019z yog\u2019lariga o\u2019zlari qovurilmaydilar; inson axloqning jismoniy  holatinigina  og\u2019irlashtiradi", "tadqiqotlardan aniqlanishicha, stress inson organizmini noxush o\u2019zgarishlarga olib keladi, buning natijasida psixikadan mustasno  buzilishlar (o\u2019zgarishlar) ro\u2019y beradi; odamlar faol hayot tarzidan bosh tortib, o\u2019z yog\u2019lariga o\u2019zlari qovurilmaydilar;inson axloqning jismoniy  va ruhiy holatini  og\u2019irlashtiradi"], "correct": 0},
  {"question": "Menejerlar ishidagi stress sabablari ifoda eting.", "answers": ["tijoratda har qanday boshlab berilgan ish (tashabbus)-doimo qaltis ish qilish(tavakkal qilish) demak va kuchli asabiy tazyiq  sharoitidagi ish,o\u2019zining ketidan, albatta, iz qoldiradi. \u201cBoylikni tuzoqqa tushirish\u201d(\u201cBoylik tuzog\u2019i\u201d). Yo\u2019qotishdan hadiksirash (qo\u2019rqish)-oila, mol-mulk, pullarni. \u201cIdeallarni yo\u2019qotish kasalligi\u201d.  \u201cOrtiqcha sermehnatlilik\u201d(ishga ko\u2019milib ketish, mehnatga shaydo bo\u2019lish), bunda yaqinlari va  o\u2019z-o\u2019zi bilan aloqasi uziladi, kishining shaxsiy o\u2019tmishi o\u2019ziga begona bo\u2019lib qoladi. \u201cIshdagi bosh-keti yo\u2019qlik (boshboshdoqlik)\u201d-ishdagi o\u2019taketgan tartibsizlik. Bunday odamlar kerakli buyumlarini topa olmay, hamisha asabiylashadilar, qolib ketgan ishni eslab, sarosimaga tushaveradilar, bir u-bir bu ishga qo\u2019l uradilar, muntazam ravishda kechikib yuradilar", "\u201cBoylikni tuzoqqa tushirish\u201d (\u201cBoylik tuzog\u2019i\u201d). Yo\u2019qotishdan hadiksirash (qo\u2019rqish)-oila, mol-mulk, pullarni.  \u201cIdeallarni yo\u2019qotish kasalligi\u201d. \u201cIshdagi bosh-keti yo\u2019qlik (boshboshdoqlik)\u201d-ishdagi o\u2019taketgan tartibsizlik. Bunday odamlar kerakli buyumlarini topa olmay, hamisha asabiylashadilar, bir u-bir bu ishga qo\u2019l uradilar, muntazam ravishda kechikib yuradilar", "Yo\u2019qotishdan hadiksirash (qo\u2019rqish)-oila, mol-mulk, pullarni. \u201cIshdagi bosh-keti yo\u2019qlik (boshboshdoqlik)\u201d-ishdagi o\u2019taketgan tartib bosimi. Bunday odamlar kerakli vositalarni topa olmay, hamisha asabiylashadilar, bajarilgan ishni eslab, sarosimaga tushaveradilar, bir u - bir bu ishga qo\u2019l uradilar, muntazam ravishda ishga barvaqt keladilar", " \u201cOrtiqcha sermehnatlilik\u201d(ishga ko\u2019milib ketish, mehnatga shaydo bo\u2019lish), bunda yaqinlari va  o\u2019z-o\u2019zi bilan aloqasi o\u2019rnatiladi, kishining shaxsiy o\u2019tmishi o\u2019ziga begona bo\u2019lib qolmaydi. Bunday odamlar kerakli vositalarni topa olmay, hamisha asabiylashadilar, bajarilgan ishni eslab, sarosimaga tushaveradilar, bir u - bir bu ishga qo\u2019l uradilar, muntazam ravishda ishdan barvaqt etib,  ishga kechikib keladilar"], "correct": 0},
  {"question": "Stressga olib keladigan omillar nechta va qanday shartli guruhlarga bo\u2019linadi?", "answers": ["stressga olib keladigan omillarni shartli uch guruhga ajratish mumkin. Tashqi omillar. Tashkilot bilan bog\u2019liq omillar. Odamning o\u2019zi bilan bog\u2019liq  omillar", "stressga olib keladigan omillarni shartli uch guruhga ajratish mumkin. Tashqi omillar. Tashkilot bilan bog\u2019liq bo\u2019lmagan omillar. Odamning o\u2019zi bilan bog\u2019liq  omillar", "stressga olib keladigan omillarni shartli uch guruhga ajratish mumkin. Tashqi omillar. Tashkilot bilan bog\u2019liq bo\u2019lmagan omillar. Odamning o\u2019zi bilan bog\u2019liq bo\u2019lmagan  omillar", "stressga olib keladigan omillarni shartli uch guruhga ajratish mumkin. Tashqi muhit bilan bog\u2019liq bo\u2019lmagan omillar. Tashkilot bilan bog\u2019liq bo\u2019lmagan omillar. damning o\u2019zi bilan bog\u2019liq bo\u2019lmagan  omillar"], "correct": 0},
  {"question": "Odamlar stresslarga bardoshlilik darajasiga ko\u2019ra o\u2019ziga xos qanday tipga ajratiladi?", "answers": ["\u201cA\u201d tip o\u2019zining shu xususiyati bilan farqlanadiki, u oldinda bo\u2019lishga doimiy intilish hissini tuyadi; qat\u2019iy ravishda o\u2019z maqsadiga erishishni xohlaydi, bellashuvda qatnashishni(musobaqalashish, kuch sinashishni) va hammaning ustidan g\u2019olib kelish ehtiyojini his qiladi; har doim birdaniga ko\u2019p ishlar bilan band bo\u2019ladi; odatda shoshgani-shoshgan; ishlar sur\u2019atini tezlatishga harakat qiladi; qattiq bezovtalanish holatida yuradi. Bunday odam koronar tiplarga mansub bo\u2019lib, stressga chalinish moyilligi kuchlidir.\u201dB\u201d tip naqd \u201cA\u201d tipning aksi (teskarisi). Unga stresslar kamroq ta\u2019sir o\u2019tkazadi", "\u201cA\u201d tip o\u2019zining shu xususiyati bilan farqlanadiki, u oldinda bo\u2019lishga doimiy intilish hissini tuyadi; qat\u2019iy ravishda o\u2019z manfaatlariga erishishni xohlaydi, odatda shoshgani-shoshgan; ishlar sur\u2019atini tezlatishga harakat qiladi;   \u201cB\u201d tip naqd \u201cA\u201d tipning aksi (teskarisi). Unga stresslar o\u2019rtacha ta\u2019sir o\u2019tkazadi", "\u201cB\u201d tip o\u2019zining shu xususiyati bilan farqlanadiki, u oldinda bo\u2019lishga doimiy intilish hissini tuyadi; qat\u2019iy ravishda o\u2019z manfaatlariga erishishni xohlaydi, bellashuvda qochishni (musobaqalashish, kuch sinashishni bundan mustasno) va hammaning ustidan g\u2019olib kelish ehtiyojini his qiladi; har doim birdaniga ko\u2019p ishlar bilan band bo\u2019lishni hohlamaydi; odatda shoshgani-shoshgan; ishlar sur\u2019atini pasayirishga harakat qiladi; qattiq bezovtalanish holatida yuradi. Bunday odam koronar tiplarga mansub bo\u2019lib, stressga chalinish moyilligi kuchlidir.\u201dA\u201d tip naqd \u201cB\u201d tipning aksi (teskarisi). Unga stresslar kamroq ta\u2019sir o\u2019tkazadi", "\u201cA\u201d tip o\u2019zining shu xususiyati bilan farqlanadiki, u oldinda bo\u2019lishga doimiy intilish hissini tuyadi; qat\u2019iy ravishda o\u2019z manfaatlariga erishishni xohlaydi, ishlar sur\u2019atini pasayirishga harakat qiladi; qattiq bezovtalanish holatida yuradi. Bunday odam koronar tiplarga mansub bo\u2019lib, stressga chalinish moyilligi kuchsizdir.\u201dB\u201d tip naqd \u201cA\u201d tipning aksi (teskarisi). Unga stresslar samarali ta\u2019sir o\u2019tkazadi"], "correct": 0},
  {"question": "Stressning boshqarilishida qanday usullardan foydalanish taxmin qilinadi?", "answers": ["stressning boshqarilishida uning oldini olish(profilaktikasi) usullaridan foydalanish taxmin qilinadi. Keng tarqalgan usullaridan biri-dam olish(ammo, bunda hech narsa qilish kerak emas, degan fikr bildirilmaydi). Ruhiyatning ko\u2019tarinkiligi(vaqti chog\u2019lik, yaxshi kayfiyat)ga kelib  olish va uni bir maromda ushlab turish mashqlarini qo\u2019llash- uning muhim vositasi", "stressning boshqarilishida keng tarqalgan usullaridan biri-dam olish(ammo, bunda hech narsa qilish kerak, degan fikr bildirilmaydi). Ruhiyatning ko\u2019tarinkiligi(vaqti chog\u2019lik, yaxshi kayfiyat)ga kelib  olish va uni bir maromda ushlab turish mashqlarini qo\u2019llash- uning muhim vositasi", "stressning boshqarilishida ruhiyatning ko\u2019tarinkiligi ta\u2019minlash (vaqti chog\u2019lik, yaxshi kayfiyat)ga kelib  olish va uni bir maromda ushlab turish uchun korxona ma\u2019muriyati bilan bir to\u2019htamga kelish - uning muhim vositasi", "stressning boshqarilishida ruhiyatni bir maromda ushlab turish uchun korxona rahbariyati va egasi  bilan o\u2019zaro manfaatli shartnomalar tuzish - uning muhim vositasi"], "correct": 0},
  {"question": "Stressning oldini olish va engish yo\u2019llarini topish   qanday xarakterga ega bo\u2019lishi kerak?", "answers": ["stressning oldini olish va engish yo\u2019llarini topish-ham tashkilot darajasida, ham shaxs darajasida amalga oshirilishi shart.Birinchi darajada- quyidagilar hisobiga amalga oshiriladi: kadrlarning to\u2019g\u2019ri tanlanishi va bilib, o\u2019z o\u2019rniga qo\u2019yilishi, aniq va bajarilishi to\u2019g\u2019ri, deb topilgan masalalarning ko\u2019rsatilishi, ishonchli loyihalashtirilgan ishlar, jamoa a\u2019zolari bilan birgalikda qabul qilingan qarorlar, shuningdek, ishchilarning salomatligini tiklash(sog\u2019lomlashtirish) dasturini amalga tatbiq etish", "stressning oldini olish va engish uchun kadrlarning to\u2019g\u2019ri tanlanishi va bilib, o\u2019z o\u2019rniga qo\u2019yilishi, aniq va bajarilishi to\u2019g\u2019ri, deb topilgan masalalarning ko\u2019rsatilishi, ishonchli loyihalashtirilgan ishlar, jamoa a\u2019zolari bilan birgalikda qabul qilingan qarorlar, shuningdek, ishchilarning salomatligini tiklash(sog\u2019lomlashtirish) dasturini amalga tatbiq etish", "stressning oldini olish va engish yo\u2019llarini topish-ham tashkilot darajasida, ham shaxs darajasida amalga oshirilishi ancha mushkul", "stressning oldini olish va engish yo\u2019llarini topish-ham tashkilot darajasida, ham shaxs darajasida amalga oshirilishi uchun ishonchli loyihalashtirilgan ishlar, demokratik prinsiplarda qabul qilingan qarorlar, shuningdek, ishchilarning ishchanligini tiklash (sog\u2019lomlashtirish) dasturini amalga tatbiq etish"], "correct": 0}
]

# ============ BOT HANDLERLARI ============

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "👋 Assalomu alaykum!\n\n"
        "📚 *Tashkiliy Xulq* fanidan test botiga xush kelibsiz!\n\n"
        "🎯 Har testda 20 ta savol beriladi\n"
        "✅ To'g'ri javob yashil belgilanadi\n"
        "❌ Noto'g'ri javobda to'g'ri javob ko'rsatiladi\n\n"
        "Boshlash uchun /test buyrug'ini yuboring!",
        parse_mode="Markdown"
    )

async def test_start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    selected = random.sample(QUESTIONS, QUESTIONS_PER_TEST)
    context.user_data['questions'] = selected
    context.user_data['current'] = 0
    context.user_data['score'] = 0
    await send_question(update, context)

async def send_question(update: Update, context: ContextTypes.DEFAULT_TYPE):
    questions = context.user_data['questions']
    idx = context.user_data['current']
    q = questions[idx]

    letters = ['A', 'B', 'C', 'D']
    keyboard = [
        [InlineKeyboardButton(f"{letters[i]}) {a[:50]}{'...' if len(a)>50 else ''}", callback_data=str(i))]
        for i, a in enumerate(q['answers'])
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)

    text = f"❓ *Savol {idx+1}/{QUESTIONS_PER_TEST}*\n\n{q['question']}"

    if update.callback_query:
        await update.callback_query.message.reply_text(text, reply_markup=reply_markup, parse_mode="Markdown")
    else:
        await update.message.reply_text(text, reply_markup=reply_markup, parse_mode="Markdown")

async def handle_answer(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()

    if 'questions' not in context.user_data:
        await query.message.reply_text("Yangi test boshlash uchun /test yuboring.")
        return

    chosen = int(query.data)
    questions = context.user_data['questions']
    idx = context.user_data['current']
    q = questions[idx]
    correct = q['correct']
    letters = ['A', 'B', 'C', 'D']

    if chosen == correct:
        context.user_data['score'] += 1
        result_text = f"✅ *To'g'ri!*\n\n📌 {q['answers'][correct]}"
    else:
        result_text = (
            f"❌ *Noto'g'ri!*\n\n"
            f"Siz tanladingiz: {letters[chosen]}) {q['answers'][chosen]}\n\n"
            f"✅ To'g'ri javob: {letters[correct]}) {q['answers'][correct]}"
        )

    await query.message.edit_reply_markup(reply_markup=None)
    context.user_data['current'] += 1

    if context.user_data['current'] >= QUESTIONS_PER_TEST:
        score = context.user_data['score']
        total = QUESTIONS_PER_TEST
        percent = int(score / total * 100)

        if percent >= 86:
            baho = "5 (A'lo) 🏆"
        elif percent >= 71:
            baho = "4 (Yaxshi) 👍"
        elif percent >= 56:
            baho = "3 (Qoniqarli) 😐"
        else:
            baho = "2 (Qoniqarsiz) ❗"

        await query.message.reply_text(result_text, parse_mode="Markdown")
        await query.message.reply_text(
            f"🏁 *Test yakunlandi!*\n\n"
            f"✅ To'g'ri: {score}/{total}\n"
            f"📊 Foiz: {percent}%\n"
            f"📝 Baho: {baho}\n\n"
            f"Qayta urinish uchun /test yuboring!",
            parse_mode="Markdown"
        )
        context.user_data.clear()
    else:
        await query.message.reply_text(result_text, parse_mode="Markdown")
        await send_question(update, context)

def main():
    app = Application.builder().token(TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("test", test_start))
    app.add_handler(CallbackQueryHandler(handle_answer))
    print("✅ Bot ishga tushdi!")
    app.run_polling()

if __name__ == "__main__":
    main()
